### ISSUE TITLE
Przeniesienie połączenia do bazy do osobnego pliku

### ISSUE THREAD

**Issue by szygmon** [ZSET-Leszno/wiki-enter-the-gungeon#5]
np. config php z danymi do bazy (host, użytkownik, hasło, baza), w plikach które z BD korzystają dać include i pod spodem tylko samo mysqli_connect + zapytania. Przy aktualnym podejściu zmiana bazy wymaga zmiany w każdym pliku, a tak będzie tylko w configu.

**Comment by Bruczu** [comment]
stworzono plik config.php według wytycznych
